COC = {
    'WC': {
        '1Herbrumer': {'QB': 'Herbert', 'RB': 'Barkley', 'WR': 'Nacua', 'TE': 'Kraft'}, 
        'bakerbarkley': {'QB': 'Daniels', 'RB': 'Barkley', 'WR': 'McMillan', 'TE': 'Kraft'}, 
        'BassBert': {'QB': 'Daniels', 'RB': 'Irving', 'WR': 'Jefferson', 'TE': 'Kincaid'}, 
        'beastm0de': {'QB': 'Herbert', 'RB': 'Barkley', 'WR': 'Nacua', 'TE': 'Kraft'}, 
        'blackpanda4255': {'QB': 'Herbert', 'RB': 'Barkley', 'WR': 'Nacua', 'TE': 'Kraft'}, 
        'block_west18': {'QB': 'Herbert', 'RB': 'Barkley', 'WR': 'Nacua', 'TE': 'Kraft'}, 
        'Bummi': {'QB': 'Daniels', 'RB': 'Irving', 'WR': 'Jefferson', 'TE': 'Kincaid'}, 
        'chaefer77': {'QB': 'Daniels', 'RB': 'Irving', 'WR': 'Nacua', 'TE': 'Kraft'}, 
        'copyk': {'QB': 'Nix', 'RB': 'Barkley', 'WR': 'Nacua', 'TE': 'Kincaid'}, 
        'DanTheMan84': {'QB': 'Daniels', 'RB': 'Irving', 'WR': 'Nacua', 'TE': 'Kraft'}, 
        'Deckhard': {'QB': 'Daniels', 'RB': 'Irving', 'WR': 'Jefferson', 'TE': 'Kincaid'}, 
        'Effe A.': {'QB': 'Daniels', 'RB': 'Irving', 'WR': 'Jefferson', 'TE': 'Kincaid'}, 
        'elpres': {'QB': 'Daniels', 'RB': 'Williams', 'WR': 'Nacua', 'TE': 'Kincaid'}, 
        'fa94': {'QB': 'Herbert', 'RB': 'Barkley', 'WR': 'Nacua', 'TE': 'Kraft'}, 
        'fredie_io': {'QB': 'Herbert', 'RB': 'Barkley', 'WR': 'Nacua', 'TE': 'Kraft'}, 
        'Hans Hansen': {'QB': 'Jackson', 'RB': 'Irving', 'WR': 'Nacua', 'TE': 'Kincaid'},
        'haube37': {'QB': 'Nix', 'RB': 'Irving', 'WR': 'Nacua', 'TE': 'Kraft'}, 
        'herbstibears': {'QB': 'Nix', 'RB': 'Irving', 'WR': 'Jefferson', 'TE': 'Kraft'}, 
        'Hiase': {'QB': 'Daniels', 'RB': 'Barkley', 'WR': 'Sutton', 'TE': 'Kincaid'}, 
        'Immortellus': {'QB': 'Daniels', 'RB': 'Barkley', 'WR': 'Sutton', 'TE': 'Kincaid'}, 
        'JackPOT': {'QB': 'Herbert', 'RB': 'Barkley', 'WR': 'Nacua', 'TE': 'Kraft'}, 
        'jans12': {'QB': 'Daniels', 'RB': 'Irving', 'WR': 'Jefferson', 'TE': 'Kincaid'}, 
        'KingCookie': {'QB': 'Herbert', 'RB': 'Barkley', 'WR': 'Nacua', 'TE': 'Kraft'}, 
        'kunfc.': {'QB': 'Jackson', 'RB': 'Williams', 'WR': 'Sutton', 'TE': 'Kincaid'}, 
        'Lambo23': {'QB': 'Herbert', 'RB': 'Williams', 'WR': 'Jefferson', 'TE': 'Kraft'}, 
        'LeTomster': {'QB': 'Herbert', 'RB': 'Barkley', 'WR': 'Nacua', 'TE': 'Kraft'}, 
        'luckenbuesser': {'QB': 'Daniels', 'RB': 'Mixon', 'WR': 'Jefferson', 'TE': 'Kraft'}, 
        'Lunatic': {'QB': 'Nix', 'RB': 'Barkley', 'WR': 'Nacua', 'TE': 'Kincaid'}, 
        'Marcello': {'QB': 'Daniels', 'RB': 'Irving', 'WR': 'Nacua', 'TE': 'Kraft'}, 
        'marvhin23': {'QB': 'Daniels', 'RB': 'Williams', 'WR': 'Nacua', 'TE': 'Kincaid'}, 
        'Matze Luki': {'QB': 'Jackson', 'RB': 'Irving', 'WR': 'Nacua', 'TE': 'Kincaid'}, 
        'MCO': {'QB': 'Herbert', 'RB': 'Barkley', 'WR': 'Sutton', 'TE': 'Freiermuth'}, 
        'Merlyn112': {'QB': 'Daniels', 'RB': 'Barkley', 'WR': 'Sutton', 'TE': 'Kincaid'}, 
        'Mirarot': {'QB': 'Jackson', 'RB': 'Irving', 'WR': 'Nacua', 'TE': 'Kincaid'}, 
        'mogli_dk': {'QB': 'Daniels', 'RB': 'Barkley', 'WR': 'McMillan', 'TE': 'Kraft'}, 
        'Neyinoo': {'QB': 'Daniels', 'RB': 'Irving', 'WR': 'Jefferson', 'TE': 'Kincaid'}, 
        'Pascal': {'QB': 'Herbert', 'RB': 'Barkley', 'WR': 'Nacua', 'TE': 'Kraft'}, 
        'pate1703': {'QB': 'Daniels', 'RB': 'Barkley', 'WR': 'Sutton', 'TE': 'Kincaid'}, 
        'PatKau1904': {'QB': 'Herbert', 'RB': 'Barkley', 'WR': 'Nacua', 'TE': 'Kraft'}, 
        'philadeagles': {'QB': 'Nix', 'RB': 'Barkley', 'WR': 'McMillan', 'TE': 'Freiermuth'}, 
        'Ptough(Pete)': {'QB': 'Herbert', 'RB': 'Barkley', 'WR': 'Nacua', 'TE': 'Kraft'},
        'SchlagiUSR': {'QB': 'Herbert', 'RB': 'Barkley', 'WR': 'Nacua', 'TE': 'Kraft'}, 
        'Stoni': {'QB': 'Jackson', 'RB': 'Irving', 'WR': 'Nacua', 'TE': 'Kincaid'}, 
        'Tsubasa': {'QB': 'Herbert', 'RB': 'Barkley', 'WR': 'Nacua', 'TE': 'Kraft'}, 
        'wiglgrimpft': {'QB': 'Nix', 'RB': 'Irving', 'WR': 'Sutton', 'TE': 'Andrews'}, 
        'xhailmurray': {'QB': 'Daniels', 'RB': 'Barkley', 'WR': 'McMillan', 'TE': 'Kraft'}, 
        'ys_db_21': {'QB': 'Daniels', 'RB': 'Irving', 'WR': 'Nacua', 'TE': 'Kraft'}
    },
    'DR': {
        '1Herbrumer': {'QB': 'Goff', 'RB': 'Gibbs', 'WR': 'McLaurin', 'TE': 'Ertz'}, 
        'bakerbarkley': {'QB': 'Allen', 'RB': 'Cook', 'WR': 'Collins', 'TE': 'Ertz'}, 
        'BassBert': {'QB': 'Allen', 'RB': 'Gibbs', 'WR': 'Williams', 'TE': 'Goedert'}, 
        'beastm0de': {'QB': 'Goff', 'RB': 'Gibbs', 'WR': 'McLaurin', 'TE': 'Ertz'}, 
        'blackpanda4255': {'QB': '', 'RB': '', 'WR': '', 'TE': ''},
        'block_west18': {'QB': 'Allen', 'RB': 'Cook', 'WR': 'Williams', 'TE': 'Kelce'}, 
        'Bummi': {'QB': 'Allen', 'RB': 'Gibbs', 'WR': 'Williams', 'TE': 'Ertz'}, 
        'chaefer77': {'QB': 'Goff', 'RB': 'Henry', 'WR': 'Smith', 'TE': ''}, 
        'copyk': {'QB': 'Mahomes', 'RB': 'Gibbs', 'WR': 'Williams', 'TE': 'Kelce'}, 
        'DanTheMan84': {'QB': 'Allen', 'RB': 'Gibbs', 'WR': 'Williams', 'TE': 'Goedert'}, 
        'Deckhard': {'QB': 'Allen', 'RB': 'Cook', 'WR': 'Collins', 'TE': 'Ertz'}, 
        'Effe A.': {'QB': 'Mahomes', 'RB': 'Henry', 'WR': 'Williams', 'TE': 'Goedert'}, 
        'elpres': {'QB': 'Goff', 'RB': 'Gibbs', 'WR': 'Williams', 'TE': 'LaPorta'}, 
        'fa94': {'QB': 'Goff', 'RB': 'Gibbs', 'WR': 'McLaurin', 'TE': 'Ertz'}, 
        'fredie_io': {'QB': '', 'RB': '', 'WR': '', 'TE': ''}, 
        'Hans Hansen': {'QB': 'Allen', 'RB': 'Gibbs', 'WR': 'Williams', 'TE': 'Kelce'}, 
        'haube37': {'QB': 'Allen', 'RB': 'Gibbs', 'WR': 'Williams', 'TE': 'Goedert'}, 
        'herbstibears': {'QB': 'Stafford', 'RB': 'Gibbs', 'WR': 'Collins', 'TE': 'Kelce'}, 
        'Hiase': {'QB': 'Mahomes', 'RB': 'Henry', 'WR': 'Williams', 'TE': 'Goedert'},
        'Immortellus': {'QB': 'Allen', 'RB': 'Gibbs', 'WR': 'Williams', 'TE': 'Ertz'}, 
        'JackPOT': {'QB': 'Allen', 'RB': 'Gibbs', 'WR': 'Williams', 'TE': 'Goedert'}, 
        'jans12': {'QB': 'Mahomes', 'RB': 'Henry', 'WR': 'Williams', 'TE': 'Goedert'}, 
        'KingCookie': {'QB': 'Allen', 'RB': 'Gibbs', 'WR': 'Williams', 'TE': 'Goedert'}, 
        'kunfc.': {'QB': 'Mahomes', 'RB': 'Gibbs', 'WR': 'Collins', 'TE': 'Ertz'},
        'Lambo23': {'QB': 'Mahomes', 'RB': 'Gibbs', 'WR': 'Williams', 'TE': 'Kelce'},
        'LeTomster': {'QB': 'Goff', 'RB': 'Gibbs', 'WR': 'McLaurin', 'TE': 'Ertz'},
        'luckenbuesser': {'QB': 'Allen', 'RB': 'Gibbs', 'WR': 'Williams', 'TE': 'Goedert'},
        'Lunatic': {'QB': '', 'RB': '', 'WR': '', 'TE': ''}, 
        'Marcello': {'QB': 'Allen', 'RB': 'Gibbs', 'WR': 'Williams', 'TE': 'Goedert'},
        'marvhin23': {'QB': 'Allen', 'RB': 'Gibbs', 'WR': 'Smith', 'TE': 'Ertz'},
        'Matze Luki': {'QB': 'Goff', 'RB': 'Henry', 'WR': 'Collins', 'TE': 'Ertz'},
        'MCO': {'QB': 'Mahomes', 'RB': 'Henry', 'WR': 'Williams', 'TE': 'Goedert'},
        'Merlyn112': {'QB': 'Goff', 'RB': 'Gibbs', 'WR': 'Collins', 'TE': 'Goedert'}, 
        'Mirarot': {'QB': 'Allen', 'RB': 'Gibbs', 'WR': 'Williams', 'TE': 'Ertz'}, 
        'mogli_dk': {'QB': 'Goff', 'RB': 'Henry', 'WR': 'Williams', 'TE': 'Kelce'}, 
        'Neyinoo': {'QB': 'Allen', 'RB': 'Gibbs', 'WR': 'Smith', 'TE': 'Ertz'}, 
        'Pascal': {'QB': '', 'RB': '', 'WR': '', 'TE': ''}, 
        'pate1703': {'QB': 'Allen', 'RB': 'Gibbs', 'WR': 'Williams', 'TE': 'Goedert'}, 
        'PatKau1904': {'QB': 'Goff', 'RB': 'Henry', 'WR': 'Collins', 'TE': 'Ertz'}, 
        'philadeagles': {'QB': 'Goff', 'RB': 'Gibbs', 'WR': 'Williams', 'TE': 'LaPorta'},
        'Ptough(Pete)': {'QB': 'Goff', 'RB': 'Henry', 'WR': 'Williams', 'TE': 'Kelce'}, 
        'SchlagiUSR': {'QB': 'Goff', 'RB': 'Gibbs', 'WR': 'McLaurin', 'TE': 'Ertz'}, 
        'Stoni': {'QB': 'Allen', 'RB': 'Gibbs', 'WR': 'Williams', 'TE': 'Goedert'}, 
        'Tsubasa': {'QB': 'Mahomes', 'RB': 'Gibbs', 'WR': 'Williams', 'TE': 'Kelce'}, 
        'wiglgrimpft': {'QB': 'Allen', 'RB': 'Gibbs', 'WR': 'Smith', 'TE': 'Ertz'}, 
        'xhailmurray': {'QB': 'Goff', 'RB': 'Gibbs', 'WR': 'McLaurin', 'TE': 'Ertz'}, 
        'ys_db_21': {'QB': 'Goff', 'RB': 'Gibbs', 'WR': 'Collins', 'TE': 'Ertz'}
    }, 
    'CF': {
        '1Herbrumer': {'QB': '', 'RB': '', 'WR': '', 'TE': ''}, 
        'bakerbarkley': {'QB': 'Daniels', 'RB': 'Eagles', 'WR': 'Bills', 'TE': 'Kincaid'}, 
        'BassBert': {'QB': 'Daniels', 'RB': 'Commanders', 'WR': 'Eagles', 'TE': 'Kincaid'}, 
        'beastm0de': {'QB': '', 'RB': '', 'WR': '', 'TE': ''}, 
        'blackpanda4255': {'QB': '', 'RB': '', 'WR': '', 'TE': ''}, 
        'block_west18': {'QB': 'Daniels', 'RB': 'Eagles', 'WR': 'Chiefs', 'TE': 'Kincaid'}, 
        'Bummi': {'QB': 'Daniels', 'RB': 'Eagles', 'WR': 'Chiefs', 'TE': 'Kincaid'}, 
        'chaefer77': {'QB': 'Daniels', 'RB': 'Chiefs', 'WR': 'Commanders', 'TE': 'Ertz'}, 
        'copyk': {'QB': 'Mahomes', 'RB': 'Eagles', 'WR': 'Commanders', 'TE': 'Goedert'}, 
        'DanTheMan84': {'QB': 'Allen', 'RB': 'Commanders', 'WR': 'Commanders', 'TE': 'Kincaid'}, 
        'Deckhard': {'QB': 'Allen', 'RB': 'Chiefs', 'WR': 'Commanders', 'TE': 'Goedert'}, 
        'Effe A.': {'QB': 'Allen', 'RB': 'Chiefs', 'WR': 'Commanders', 'TE': 'Goedert'}, 
        'elpres': {'QB': 'Mahomes', 'RB': 'Eagles', 'WR': 'Commanders', 'TE': 'Goedert'}, 
        'fa94': {'QB': '', 'RB': '', 'WR': '', 'TE': ''}, 
        'fredie_io': {'QB': '', 'RB': '', 'WR': '', 'TE': ''}, 
        'Hans Hansen': {'QB': 'Mahomes', 'RB': 'Eagles', 'WR': 'Commanders', 'TE': 'Goedert'}, 
        'haube37': {'QB': 'Mahomes', 'RB': 'Eagles', 'WR': 'Commanders', 'TE': 'Kincaid'}, 
        'herbstibears': {'QB': '', 'RB': '', 'WR': '', 'TE': ''}, 
        'Hiase': {'QB': 'Daniels', 'RB': 'Chiefs', 'WR': 'Eagles', 'TE': 'Kincaid'}, 
        'Immortellus': {'QB': 'Daniels', 'RB': 'Commanders', 'WR': 'Bills', 'TE': 'Kelce'}, 
        'JackPOT': {'QB': 'Mahomes', 'RB': 'Eagles', 'WR': 'Commanders', 'TE': 'Goedert'}, 
        'jans12': {'QB': 'Mahomes', 'RB': 'Chiefs', 'WR': 'Chiefs', 'TE': 'Kelce'}, 
        'KingCookie': {'QB': 'Daniels', 'RB': 'Eagles', 'WR': 'Chiefs', 'TE': 'Kincaid'}, 
        'kunfc.': {'QB': 'Mahomes', 'RB': 'Eagles', 'WR': 'Commanders', 'TE': 'Goedert'}, 
        'Lambo23': {'QB': 'Mahomes', 'RB': 'Eagles', 'WR': 'Commanders', 'TE': 'Goedert'}, 
        'LeTomster': {'QB': 'Mahomes', 'RB': 'Eagles', 'WR': 'Commanders', 'TE': 'Goedert'}, 
        'luckenbuesser': {'QB': 'Hurts', 'RB': 'Bills', 'WR': 'Bills', 'TE': 'Kelce'}, 
        'Lunatic': {'QB': '', 'RB': '', 'WR': '', 'TE': ''}, 
        'Marcello': {'QB': 'Mahomes', 'RB': 'Commanders', 'WR': 'Commanders', 'TE': 'Kelce'}, 
        'marvhin23': {'QB': '', 'RB': '', 'WR': '', 'TE': ''}, 
        'Matze Luki': {'QB': 'Daniels', 'RB': 'Eagles', 'WR': 'Bills', 'TE': 'Goedert'}, 
        'MCO': {'QB': '', 'RB': '', 'WR': '', 'TE': ''}, 
        'Merlyn112': {'QB': 'Daniels', 'RB': 'Commanders', 'WR': 'Eagles', 'TE': 'Kincaid'}, 
        'Mirarot': {'QB': 'Allen', 'RB': 'Commanders', 'WR': 'Commanders', 'TE': 'Kincaid'},
        'mogli_dk': {'QB': 'Hurts', 'RB': 'Commanders', 'WR': 'Eagles', 'TE': 'Kincaid'},
        'Neyinoo': {'QB': 'Mahomes', 'RB': 'Eagles', 'WR': 'Chiefs', 'TE': 'Ertz'}, 
        'Pascal': {'QB': '', 'RB': '', 'WR': '', 'TE': ''}, 
        'pate1703': {'QB': 'Daniels', 'RB': 'Bills', 'WR': 'Commanders', 'TE': 'Kincaid'}, 
        'PatKau1904': {'QB': 'Daniels', 'RB': 'Bills', 'WR': 'Commanders', 'TE': 'Kincaid'},
        'philadeagles': {'QB': 'Daniels', 'RB': 'Chiefs', 'WR': 'Eagles', 'TE': 'Goedert'}, 
        'Ptough(Pete)': {'QB': 'Mahomes', 'RB': 'Eagles', 'WR': 'Commanders', 'TE': 'Kincaid'}, 
        'SchlagiUSR': {'QB': 'Mahomes', 'RB': 'Eagles', 'WR': 'Commanders', 'TE': 'Kincaid'}, 
        'Stoni': {'QB': 'Daniels', 'RB': 'Eagles', 'WR': 'Chiefs', 'TE': 'Kincaid'}, 
        'Tsubasa': {'QB': 'Hurts', 'RB': 'Bills', 'WR': 'Commanders', 'TE': 'Goedert'}, 
        'wiglgrimpft': {'QB': 'Allen', 'RB': 'Bills', 'WR': 'Bills', 'TE': 'Kincaid'}, 
        'xhailmurray': {'QB': 'Daniels', 'RB': 'Commanders', 'WR': 'Commanders', 'TE': 'Goedert'}, 
        'ys_db_21': {'QB': 'Hurts', 'RB': 'Bills', 'WR': 'Commanders', 'TE': 'Goedert'}
    }, 
    'SB': {
        '1Herbrumer': {'Player1': '', 'Player2': '', 'Player3': ''}, 
        'bakerbarkley': {'Player1': 'Hurts', 'Player2': 'Goedert', 'Player3': 'Schuster'}, 
        'BassBert': {'Player1': '', 'Player2': '', 'Player3': ''},
        'beastm0de': {'Player1': '', 'Player2': '', 'Player3': ''}, 
        'blackpanda4255': {'Player1': '', 'Player2': '', 'Player3': ''},
        'block_west18': {'Player1': 'Brown', 'Player2': 'Hunt', 'Player3': 'Butker'}, 
        'Bummi': {'Player1': 'Brown', 'Player2': 'Pacheco', 'Player3': 'Butker'}, 
        'chaefer77': {'Player1': 'Worthy', 'Player2': 'Smith', 'Player3': 'Hunt'},
        'copyk': {'Player1': 'Worthy', 'Player2': 'Hunt', 'Player3': 'Butker'}, 
        'DanTheMan84': {'Player1': 'Worthy', 'Player2': 'Hunt', 'Player3': 'Goedert'}, 
        'Deckhard': {'Player1': 'Brown', 'Player2': 'Hunt', 'Player3': 'Butker'}, 
        'Effe A.': {'Player1': '', 'Player2': '', 'Player3': ''}, 
        'elpres': {'Player1': 'Brown', 'Player2': 'Hunt', 'Player3': 'Butker'}, 
        'fa94': {'Player1': '', 'Player2': '', 'Player3': ''}, 
        'fredie_io': {'Player1': '', 'Player2': '', 'Player3': ''}, 
        'Hans Hansen': {'Player1': 'Brown', 'Player2': 'Hunt', 'Player3': 'Butker'}, 
        'haube37': {'Player1': '', 'Player2': '', 'Player3': ''}, 
        'herbstibears': {'Player1': 'Worthy', 'Player2': 'Smith', 'Player3': 'Butker'}, 
        'Hiase': {'Player1': 'Hunt', 'Player2': 'Schuster', 'Player3': 'Butker'}, 
        'Immortellus': {'Player1': 'Worthy', 'Player2': 'Brown', 'Player3': 'Hunt'}, 
        'JackPOT': {'Player1': 'Brown', 'Player2': 'Hunt', 'Player3': 'Butker'}, 
        'jans12': {'Player1': 'Smith', 'Player2': 'Pacheco', 'Player3': 'Schuster'}, 
        'KingCookie': {'Player1': 'Worthy', 'Player2': 'Hunt', 'Player3': 'Butker'}, 
        'kunfc.': {'Player1': 'Worthy', 'Player2': 'Brown', 'Player3': 'Goedert'}, 
        'Lambo23': {'Player1': 'Barkley', 'Player2': 'Goedert', 'Player3': 'Butker'}, 
        'LeTomster': {'Player1': '', 'Player2': '', 'Player3': ''}, 
        'luckenbuesser': {'Player1': 'Smith', 'Player2': 'Pacheco', 'Player3': 'Butker'}, 
        'Lunatic': {'Player1': '', 'Player2': '', 'Player3': ''}, 
        'Marcello': {'Player1': '', 'Player2': '', 'Player3': ''}, 
        'marvhin23': {'Player1': 'Barkley', 'Player2': 'Brown', 'Player3': 'Hunt'}, 
        'Matze Luki': {'Player1': 'Brown', 'Player2': 'Hunt', 'Player3': 'Butker'}, 
        'MCO': {'Player1': '', 'Player2': '', 'Player3': ''}, 
        'Merlyn112': {'Player1': 'Worthy', 'Player2': 'Hurts', 'Player3': 'Goedert'}, 
        'Mirarot': {'Player1': '', 'Player2': '', 'Player3': ''}, 
        'mogli_dk': {'Player1': 'Smith', 'Player2': 'Mahomes', 'Player3': 'Schuster'}, 
        'Neyinoo': {'Player1': 'Brown', 'Player2': 'Hunt', 'Player3': 'Butker'}, 
        'Pascal': {'Player1': '', 'Player2': '', 'Player3': ''}, 
        'pate1703': {'Player1': 'Hurts', 'Player2': 'Goedert', 'Player3': 'Schuster'}, 
        'PatKau1904': {'Player1': '', 'Player2': '', 'Player3': ''}, 
        'philadeagles': {'Player1': 'Brown', 'Player2': 'Goedert', 'Player3': 'Butker'}, 
        'Ptough(Pete)': {'Player1': '', 'Player2': '', 'Player3': ''}, 
        'SchlagiUSR': {'Player1': '', 'Player2': '', 'Player3': ''}, 
        'Stoni': {'Player1': 'Worthy', 'Player2': 'Hurts', 'Player3': 'Butker'}, 
        'Tsubasa': {'Player1': 'Worthy', 'Player2': 'Brown', 'Player3': 'Butker'}, 
        'wiglgrimpft': {'Player1': 'Pacheco', 'Player2': 'Hunt', 'Player3': 'Butker'}, 
        'xhailmurray': {'Player1': '', 'Player2': '', 'Player3': ''}, 
        'ys_db_21': {'Player1': 'Smith', 'Player2': 'Kelce', 'Player3': 'Butker'}
    }
}

scoring_settings = {
    'pass_int': -2.0,
    # 'pass_2pt': 0,# geändert von 2
    'pass_yd': 0.04,
    'pass_td': 4.0,
    'rec_td': 6.0,
    'rec_yd': 0.1,
    # 'rec_2pt': 0,# geändert von 2
    'rec': 1.0,
    'rush_td': 6.0,
    # 'rush_2pt': 0,# geändert von 2
    'rush_yd': 0.1,
    'fum_lost': -2.0,
    'fum_rec': 2.0,
    # 'fum': 0
}

wc_round_player_by_id = {
    '4881': {'first_name': 'Lamar', 'last_name': 'Jackson', 'player_id': '4881', 'price': 5, 'position': 'QB', 'points': 0}, 
    '11566': {'first_name': 'Jayden', 'last_name': 'Daniels', 'player_id': '11566', 'price': 3, 'position': 'QB', 'points': 0}, 
    '11563': {'first_name': 'Bo', 'last_name': 'Nix', 'player_id': '11563', 'price': 1, 'position': 'QB', 'points': 0}, 
    '6797': {'first_name': 'Justin', 'last_name': 'Herbert', 'player_id': '6797', 'price': 0, 'position': 'QB', 'points': 0}, 
    '4866': {'first_name': 'Saquon', 'last_name': 'Barkley', 'player_id': '4866', 'price': 5, 'position': 'RB', 'points': 0}, 
    '8150': {'first_name': 'Kyren', 'last_name': 'Williams', 'player_id': '8150', 'price': 3, 'position': 'RB', 'points': 0}, 
    '11584': {'first_name': 'Bucky', 'last_name': 'Irving', 'player_id': '11584', 'price': 1, 'position': 'RB', 'points': 0}, 
    '4018': {'first_name': 'Joe', 'last_name': 'Mixon', 'player_id': '4018', 'price': 0, 'position': 'RB', 'points': 0}, 
    '6794': {'first_name': 'Justin', 'last_name': 'Jefferson', 'player_id': '6794', 'price': 5, 'position': 'WR', 'points': 0}, 
    '9493': {'first_name': 'Puka', 'last_name': 'Nacua', 'player_id': '9493', 'price': 3, 'position': 'WR', 'points': 0}, 
    '5045': {'first_name': 'Courtland', 'last_name': 'Sutton', 'player_id': '5045', 'price': 1, 'position': 'WR', 'points': 0}, 
    '11618': {'first_name': '', 'last_name': 'McMillan', 'player_id': '11618', 'price': 0, 'position': 'WR', 'points': 0}, 
    '5012': {'first_name': 'Mark', 'last_name': 'Andrews', 'player_id': '5012', 'price': 5, 'position': 'TE', 'points': 0}, 
    '7600': {'first_name': 'Pat', 'last_name': 'Freiermuth', 'player_id': '7600', 'price': 3, 'position': 'TE', 'points': 0}, 
    '9484': {'first_name': 'Tucker', 'last_name': 'Kraft', 'player_id': '9484', 'price': 1, 'position': 'TE', 'points': 0}, 
    '10236': {'first_name': 'Dalton', 'last_name': 'Kincaid', 'player_id': '10236', 'price': 0, 'position': 'TE', 'points': 0}
}

div_round_player_by_id = {
    '4984': {'first_name': 'Josh', 'last_name': 'Allen', 'player_id': '4984', 'price': 5, 'position': 'QB', 'points': 0}, 
    '4046': {'first_name': 'Patrick', 'last_name': 'Mahomes', 'player_id': '4046', 'price': 3, 'position': 'QB', 'points': 0}, 
    '3163': {'first_name': 'Jared', 'last_name': 'Goff', 'player_id': '3163', 'price': 1, 'position': 'QB', 'points': 0}, 
    '421': {'first_name': 'Matthew', 'last_name': 'Stafford', 'player_id': '421', 'price': 0, 'position': 'QB', 'points': 0}, 
    '3198': {'first_name': 'Derrick', 'last_name': 'Henry', 'player_id': '3198', 'price': 5, 'position': 'RB', 'points': 0}, 
    '9221': {'first_name': 'Jahmyr', 'last_name': 'Gibbs', 'player_id': '9221', 'price': 3, 'position': 'RB', 'points': 0}, 
    '8138': {'first_name': 'James', 'last_name': 'Cook', 'player_id': '8138', 'price': 1, 'position': 'RB', 'points': 0}, 
    '8154': {'first_name': 'Brian', 'last_name': 'Robinson', 'player_id': '8154', 'price': 0, 'position': 'RB', 'points': 0}, 
    '5927': {'first_name': 'Terry', 'last_name': 'McLaurin', 'player_id': '5927', 'price': 5, 'position': 'WR', 'points': 0}, 
    '7569': {'first_name': 'Nico', 'last_name': 'Collins', 'player_id': '7569', 'price': 3, 'position': 'WR', 'points': 0}, 
    '7525': {'first_name': 'Devonta', 'last_name': 'Smith', 'player_id': '7525', 'price': 1, 'position': 'WR', 'points': 0}, 
    '8148': {'first_name': 'Jameson', 'last_name': 'Williams', 'player_id': '8148', 'price': 0, 'position': 'WR', 'points': 0}, 
    '10859': {'first_name': 'Sam', 'last_name': 'LaPorta', 'player_id': '10859', 'price': 5, 'position': 'TE', 'points': 0}, 
    '1466': {'first_name': 'Travis', 'last_name': 'Kelce', 'player_id': '1466', 'price': 3, 'position': 'TE', 'points': 0}, 
    '5022': {'first_name': 'Dallas', 'last_name': 'Goedert', 'player_id': '5022', 'price': 1, 'position': 'TE', 'points': 0}, 
    '1339': {'first_name': 'Zach', 'last_name': 'Ertz', 'player_id': '1339', 'price': 0, 'position': 'TE', 'points': 0}
}

conf_round_player_by_id = {
    '4984': {'first_name': 'Josh', 'last_name': 'Allen', 'player_id': '4984', 'price': 5, 'position': 'QB', 'points': 0, 'group': 'QB'}, 
    '11566': {'first_name': 'Jayden', 'last_name': 'Daniels', 'player_id': '11566', 'price': 3, 'position': 'QB', 'points': 0, 'group': 'QB'}, 
    '6904': {'first_name': 'Jalen', 'last_name': 'Hurts', 'player_id': '6904', 'price': 1, 'position': 'QB', 'points': 0, 'group': 'QB'}, 
    '4046': {'first_name': 'Patrick', 'last_name': 'Mahomes', 'player_id': '4046', 'price': 0, 'position': 'QB', 'points': 0, 'group': 'QB'}, 
    '4866': {'first_name': 'Saquon', 'last_name': 'Barkley', 'player_id': '4866', 'price': 5, 'position': 'RB', 'points': 0, 'group': 'PHI RBs'}, 
    '7567': {'first_name': 'Kenneth', 'last_name': 'Gainwell', 'player_id': '7567', 'price': 5, 'position': 'RB', 'points': 0, 'group': 'PHI RBs'}, 
    '8138': {'first_name': 'James', 'last_name': 'Cook', 'player_id': '8138', 'price': 3, 'position': 'RB', 'points': 0, 'group': 'BUF RBs'}, 
    '11575': {'first_name': 'Ray', 'last_name': 'Davis', 'player_id': '11575', 'price': 3, 'position': 'RB', 'points': 0, 'group': 'BUF RBs'}, 
    '8154': {'first_name': 'Brian', 'last_name': 'Robinson', 'player_id': '8154', 'price': 1, 'position': 'RB', 'points': 0, 'group': 'WAS RBs'}, 
    '4663': {'first_name': 'Austin', 'last_name': 'Ekeler', 'player_id': '4663', 'price': 1, 'position': 'RB', 'points': 0, 'group': 'WAS RBs'}, 
    '8205': {'first_name': 'Isiah', 'last_name': 'Pacheco', 'player_id': '8205', 'price': 0, 'position': 'RB', 'points': 0, 'group': 'KC RBs'}, 
    '4098': {'first_name': 'Kareem', 'last_name': 'Hunt', 'player_id': '4098', 'price': 0, 'position': 'RB', 'points': 0, 'group': 'KC RBs'}, 
    '5859': {'first_name': 'AJ', 'last_name': 'Brown', 'player_id': '5859', 'price': 5, 'position': 'WR', 'points': 0, 'group': 'PHI WRs'}, 
    '7525': {'first_name': 'Devonta', 'last_name': 'Smith', 'player_id': '7525', 'price': 5, 'position': 'WR', 'points': 0, 'group': 'PHI WRs'}, 
    '5927': {'first_name': 'Terry', 'last_name': 'McLaurin', 'player_id': '5927', 'price': 3, 'position': 'WR', 'points': 0, 'group': 'WAS WRs'}, 
    '7587': {'first_name': 'Dyami', 'last_name': 'Brown', 'player_id': '7587', 'price': 3, 'position': 'WR', 'points': 0, 'group': 'WAS WRs'}, 
    '11624': {'first_name': 'Xavier', 'last_name': 'Worthy', 'player_id': '11624', 'price': 1, 'position': 'WR', 'points': 0, 'group': 'KC WRs'}, 
    '5848': {'first_name': 'Marquise', 'last_name': 'Brown', 'player_id': '5848', 'price': 1, 'position': 'WR', 'points': 0, 'group': 'KC WRs'}, 
    '2309': {'first_name': 'Amari', 'last_name': 'Cooper', 'player_id': '2309', 'price': 0, 'position': 'WR', 'points': 0, 'group': 'BUF WRs'}, 
    '8134': {'first_name': 'Kalil', 'last_name': 'Shakir', 'player_id': '8134', 'price': 0, 'position': 'WR', 'points': 0, 'group': 'BUF WRs'}, 
    '1466': {'first_name': 'Travis', 'last_name': 'Kelce', 'player_id': '1466', 'price': 5, 'position': 'TE', 'points': 0, 'group': 'TEs'}, 
    '1339': {'first_name': 'Zach', 'last_name': 'Ertz', 'player_id': '1339', 'price': 3, 'position': 'TE', 'points': 0, 'group': 'TEs'}, 
    '5022': {'first_name': 'Dallas', 'last_name': 'Goedert', 'player_id': '5022', 'price': 1, 'position': 'TE', 'points': 0, 'group': 'TEs'},
    '10236': {'first_name': 'Dalton', 'last_name': 'Kincaid', 'player_id': '10236', 'price': 0, 'position': 'TE', 'points': 0, 'group': 'TEs'}}

conf_round_groups = {
    "RB" : {
        "Eagles": ['4866', '7567'],
        "Bills": ['8138', '11575'],
        "Commanders": ['8154', '4663'],
        "Chiefs": ['8205', '4098'],
    },
    "WR" : {
        "Eagles": ['5859', '7525'],
        "Commanders": ['5927', '7587'],
        "Chiefs": ['11624', '5848'],
        "Bills": ['2309', '8134']
    }
}

super_bowl_player_by_id = {
    '6904': {'first_name': 'Jalen', 'last_name': 'Hurts', 'player_id': '6904', 'multiplikator': 1, 'position': 'QB', 'points': 0, 'group': 'PHI QB'}, 
    '4046': {'first_name': 'Patrick', 'last_name': 'Mahomes', 'player_id': '4046', 'multiplikator': 1, 'position': 'QB', 'points': 0, 'group': 'KC QB'}, 
    '1466': {'first_name': 'Travis', 'last_name': 'Kelce', 'player_id': '1466', 'multiplikator': 1, 'position': 'TE', 'points': 0, 'group': 'KC TEs'}, 
    '4866': {'first_name': 'Saquon', 'last_name': 'Barkley', 'player_id': '4866', 'multiplikator': 1, 'position': 'RB', 'points': 0, 'group': 'PHI RBs'}, 
    '11624': {'first_name': 'Xavier', 'last_name': 'Worthy', 'player_id': '11624', 'multiplikator': 3, 'position': 'WR', 'points': 0, 'group': 'KC WRs'}, 
    '7525': {'first_name': 'Devonta', 'last_name': 'Smith', 'player_id': '7525', 'multiplikator': 3, 'position': 'WR', 'points': 0, 'group': 'PHI WRs'}, 
    '5859': {'first_name': 'AJ', 'last_name': 'Brown', 'player_id': '5859', 'multiplikator': 3, 'position': 'WR', 'points': 0, 'group': 'PHI WRs'}, 
    '5022': {'first_name': 'Dallas', 'last_name': 'Goedert', 'player_id': '5022', 'multiplikator': 3, 'position': 'TE', 'points': 0, 'group': 'PHI TEs'}, 
    '8205': {'first_name': 'Isiah', 'last_name': 'Pacheco', 'player_id': '8205', 'multiplikator': 5, 'position': 'RB', 'points': 0, 'group': 'KC RBs'}, 
    '4098': {'first_name': 'Kareem', 'last_name': 'Hunt', 'player_id': '4098', 'multiplikator': 5, 'position': 'RB', 'points': 0, 'group': 'KC RBs'}, 
    '4227': {'first_name': 'Harrison', 'last_name': 'Butker', 'player_id': '4227', 'multiplikator': 5, 'position': 'K', 'points': 0, 'group': 'KC Kicker'}, 
    '4040': {'first_name': 'Juju', 'last_name': 'Smith-Schuster', 'player_id': '4040', 'multiplikator': 5, 'position': 'WR', 'points': 0, 'group': 'KC WRs'}
}